---
- hosts: localhost
  connection: local

  vars:
    device:
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

  tasks:
    - name: Create first security rule
      paloaltonetworks.panos.panos_security_rule:
        provider: '{{ device }}'
        device_group: '{{ device_group }}'
        rule_name: '{{ rule_name }}'
        source_zone: '{{ source_zone }}'
        destination_zone: '{{ destination_zone }}'
        source_ip: '{{ source_ip }}'
        destination_ip: '{{ destination_ip }}'
        application: '{{ application }}'
        service: '{{ service }}'
        description: '{{ description}}'
        #tag_name: ['Prod']
        rulebase: '{{ rulebase }}' # inventory default = post-rulebase
        action: '{{ action }}' # inventory default = allow
        target: '{{ target }}' # inventory default = any
        vsys: '{{ vsys }}' # inventory default = vsys2
        state: '{{ state }}' # inventory default = present
        commit: '{{ commit }}' # inventory default = false
